<?php

header("Content-Type: application/vnd.ms-excel");
header("Content-disposition: attachment; filename=ledger.xls");

session_start();

$username = $_SESSION['username'];
$rank = $_SESSION['rank'];
$fullname = $_SESSION['fullname'];
$chapter = $_SESSION['chapter'];

//get permission settings
require('../php/connect.php');

//function to get chapter balance
function getChapterBalance()
{
	$returnValue = 0;
	$chapter = $_SESSION['chapter'];
	require('../php/connect.php');
	$transQ = "SELECT personto, personfrom, description, amount, date FROM transactions WHERE chapter='$chapter'";
	$transR = mysqli_query($link, $transQ);
	if (!$transR){
		die('Error: ' . mysqli_error($link));
	}
	while($row = mysqli_fetch_array($transR)){
		if($row['personto'] == 'Chapter'){
			$returnValue += $row['amount'];
		}
		if($row['personfrom'] == 'Chapter'){
			$returnValue -= $row['amount'];
		}
	}
	return $returnValue;
}

	$descriptionsIncomeC = array();
	$descriptionsExpenseC = array();
	$incomeSumC = 0.00;
	$expenseSumC = 0.00;

	$descriptionsIncomeM = array();
	$descriptionsExpenseM = array();
	$incomeSumM = 0.00;
	$expenseSumM = 0.00;

	$catsQ = "SELECT personto, personfrom, description, amount, date FROM transactions WHERE chapter='$chapter'";
	$catsR = mysqli_query($link, $catsQ);
	if (!$catsR){
		die('Error: ' . mysqli_error($link));
	}

	while($row = mysqli_fetch_array($catsR)){
		//chapter balance
		if($row['personto'] == "Chapter"){
			$incomeSumC += $row['amount'];
			if(!array_key_exists($row['description'], $descriptionsIncomeC)){
				$descriptionsIncomeC[$row['description']] = $row['amount'];
			}
			else{
				$descriptionsIncomeC[$row['description']] = $descriptionsIncomeC[$row['description']] + $row['amount'];
			}
		}
		else if($row['personfrom'] == "Chapter"){
			$expenseSumC += $row['amount'];
			if(!array_key_exists($row['description'], $descriptionsExpenseC)){
				$descriptionsExpenseC[$row['description']] = $row['amount'];
			}
			else{
				$descriptionsExpenseC[$row['description']] = $descriptionsExpenseC[$row['description']] + $row['amount'];
			}
		}
		//member balance
		if($row['personto'] != "Chapter" && $row['personto'] != "Expense"){
			$incomeSumM += $row['amount'];
			if(!array_key_exists($row['description'], $descriptionsIncomeM)){
				$descriptionsIncomeM[$row['description']] = $row['amount'];
			}
			else{
				$descriptionsIncomeM[$row['description']] = $descriptionsIncomeM[$row['description']] + $row['amount'];
			}
		}
		else if($row['personfrom'] != "Chapter" && $row['personfrom'] != "Income"){
			$expenseSumM += $row['amount'];
			if(!array_key_exists($row['description'], $descriptionsExpenseM)){
				$descriptionsExpenseM[$row['description']] = $row['amount'];
			}
			else{
				$descriptionsExpenseM[$row['description']] = $descriptionsExpenseM[$row['description']] + $row['amount'];
			}
		}
	}

	echo "Chapter Audit";
	echo "\n";
	echo "\t\t\t\t";
	echo date('Y-m-d H:i:s');
	echo "\n";
	echo "\t\t\t\t";
	echo "Generated By : " . $fullname;
	echo "\n------------------------------------------------------------------------------------\nChapter Account\n------------------------------------------------------------------------------------";
	echo "\n";
	echo "\t\tIncome";
	foreach ($descriptionsIncomeC as $key => $value) {
	    echo "\n";
	    echo "\t\t\t";
	    echo "{$key} : \${$value}";
	}
	echo "\n\n";
	echo "\t\tExpenses";
	foreach ($descriptionsExpenseC as $key => $value) {
	    echo "\n";
	    echo "\t\t\t";
	    echo "{$key} : \${$value}";
	}
	echo "\n\n";
	echo "\t\tTotals";
	echo "\n";
	echo "\t\t\t";
	echo "Income : $" . $incomeSumC;
	echo "\n";
	echo "\t\t\t";
	echo "Expense : $" . $expenseSumC;
	echo "\n";
	echo "\t\t\t";
	echo "Change : $" . ($incomeSumC - $expenseSumC);
	echo "\n------------------------------------------------------------------------------------\nMember Accounts\n------------------------------------------------------------------------------------";
	echo "\n";
	echo "\t\tIncome";
	foreach ($descriptionsIncomeM as $key => $value) {
	    echo "\n";
	    echo "\t\t\t";
	    echo "{$key} : \${$value}";
	}
	echo "\n\n";
	echo "\t\tExpenses";
	foreach ($descriptionsExpenseM as $key => $value) {
	    echo "\n";
	    echo "\t\t\t";
	    echo "{$key} : \${$value}";
	}
	echo "\n\n";
	echo "\t\tTotals";
	echo "\n";
	echo "\t\t\t";
	echo "Income : $" . $incomeSumM;
	echo "\n";
	echo "\t\t\t";
	echo "Expense : $" . $expenseSumM;
	echo "\n";
	echo "\t\t\t";
	echo "Change : $" . ($incomeSumM - $expenseSumM);
	echo "\n------------------------------------------------------------------------------------\nTotal\n------------------------------------------------------------------------------------";
	echo "\n";
	echo "\t\t\t";
	echo "Chapter Balance : $" . (getChapterBalance()) . "";
	echo "\n";
	echo "\t\t\t";
	//get total user balance
	require('../php/connect.php');

	$query="SELECT SUM(balance) FROM users WHERE chapter='$chapter'";

	$result = mysqli_query($link, $query);

	if (!$result){
		die('Error: ' . mysqli_error($link));
	}
	list($cumBalance) = mysqli_fetch_array($result);
	echo "Cumulative User Balances : $" . $cumBalance;
	echo "\n";
	echo "\t\t\t";
	echo "Total Balance : $" . ($cumBalance + getChapterBalance());

?>